/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicoRouteImport } from './routes/publico'
import { Route as AppAmbientesRouteImport } from './routes/_app.ambientes'
import { Route as AppCoordenadoresRouteImport } from './routes/_app.coordenadores'
import { Route as AppCursosRouteImport } from './routes/_app.cursos'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDisciplinasRouteImport } from './routes/_app.disciplinas'
import { Route as AppDocentesRouteImport } from './routes/_app.docentes'
import { Route as AppHorariosRouteImport } from './routes/_app.horarios'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppPeriodosRouteImport } from './routes/_app.periodos'
import { Route as AppVisualizarRouteImport } from './routes/_app.visualizar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicoRoute = PublicoRouteImport.update({
  id: '/publico',
  path: '/publico',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAmbientesRoute = AppAmbientesRouteImport.update({
  id: '/ambientes',
  path: '/ambientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCoordenadoresRoute = AppCoordenadoresRouteImport.update({
  id: '/coordenadores',
  path: '/coordenadores',
  getParentRoute: () => AppRoute,
} as any)
const AppCursosRoute = AppCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplinasRoute = AppDisciplinasRouteImport.update({
  id: '/disciplinas',
  path: '/disciplinas',
  getParentRoute: () => AppRoute,
} as any)
const AppDocentesRoute = AppDocentesRouteImport.update({
  id: '/docentes',
  path: '/docentes',
  getParentRoute: () => AppRoute,
} as any)
const AppHorariosRoute = AppHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppPeriodosRoute = AppPeriodosRouteImport.update({
  id: '/periodos',
  path: '/periodos',
  getParentRoute: () => AppRoute,
} as any)
const AppVisualizarRoute = AppVisualizarRouteImport.update({
  id: '/visualizar',
  path: '/visualizar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/publico': typeof PublicoRoute
  '/ambientes': typeof AppAmbientesRoute
  '/coordenadores': typeof AppCoordenadoresRoute
  '/cursos': typeof AppCursosRoute
  '/dashboard': typeof AppDashboardRoute
  '/disciplinas': typeof AppDisciplinasRoute
  '/docentes': typeof AppDocentesRoute
  '/horarios': typeof AppHorariosRoute
  '/logs': typeof AppLogsRoute
  '/periodos': typeof AppPeriodosRoute
  '/visualizar': typeof AppVisualizarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/publico': typeof PublicoRoute
  '/ambientes': typeof AppAmbientesRoute
  '/coordenadores': typeof AppCoordenadoresRoute
  '/cursos': typeof AppCursosRoute
  '/dashboard': typeof AppDashboardRoute
  '/disciplinas': typeof AppDisciplinasRoute
  '/docentes': typeof AppDocentesRoute
  '/horarios': typeof AppHorariosRoute
  '/logs': typeof AppLogsRoute
  '/periodos': typeof AppPeriodosRoute
  '/visualizar': typeof AppVisualizarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/publico': typeof PublicoRoute
  '/_app/ambientes': typeof AppAmbientesRoute
  '/_app/coordenadores': typeof AppCoordenadoresRoute
  '/_app/cursos': typeof AppCursosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/disciplinas': typeof AppDisciplinasRoute
  '/_app/docentes': typeof AppDocentesRoute
  '/_app/horarios': typeof AppHorariosRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/periodos': typeof AppPeriodosRoute
  '/_app/visualizar': typeof AppVisualizarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/publico'
    | '/ambientes'
    | '/coordenadores'
    | '/cursos'
    | '/dashboard'
    | '/disciplinas'
    | '/docentes'
    | '/horarios'
    | '/logs'
    | '/periodos'
    | '/visualizar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/publico'
    | '/ambientes'
    | '/coordenadores'
    | '/cursos'
    | '/dashboard'
    | '/disciplinas'
    | '/docentes'
    | '/horarios'
    | '/logs'
    | '/periodos'
    | '/visualizar'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/publico'
    | '/_app/ambientes'
    | '/_app/coordenadores'
    | '/_app/cursos'
    | '/_app/dashboard'
    | '/_app/disciplinas'
    | '/_app/docentes'
    | '/_app/horarios'
    | '/_app/logs'
    | '/_app/periodos'
    | '/_app/visualizar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PublicoRoute: typeof PublicoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publico': {
      id: '/publico'
      path: '/publico'
      fullPath: '/publico'
      preLoaderRoute: typeof PublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ambientes': {
      id: '/_app/ambientes'
      path: '/ambientes'
      fullPath: '/ambientes'
      preLoaderRoute: typeof AppAmbientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coordenadores': {
      id: '/_app/coordenadores'
      path: '/coordenadores'
      fullPath: '/coordenadores'
      preLoaderRoute: typeof AppCoordenadoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cursos': {
      id: '/_app/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof AppCursosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disciplinas': {
      id: '/_app/disciplinas'
      path: '/disciplinas'
      fullPath: '/disciplinas'
      preLoaderRoute: typeof AppDisciplinasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docentes': {
      id: '/_app/docentes'
      path: '/docentes'
      fullPath: '/docentes'
      preLoaderRoute: typeof AppDocentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/horarios': {
      id: '/_app/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof AppHorariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/periodos': {
      id: '/_app/periodos'
      path: '/periodos'
      fullPath: '/periodos'
      preLoaderRoute: typeof AppPeriodosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visualizar': {
      id: '/_app/visualizar'
      path: '/visualizar'
      fullPath: '/visualizar'
      preLoaderRoute: typeof AppVisualizarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAmbientesRoute: typeof AppAmbientesRoute
  AppCoordenadoresRoute: typeof AppCoordenadoresRoute
  AppCursosRoute: typeof AppCursosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDisciplinasRoute: typeof AppDisciplinasRoute
  AppDocentesRoute: typeof AppDocentesRoute
  AppHorariosRoute: typeof AppHorariosRoute
  AppLogsRoute: typeof AppLogsRoute
  AppPeriodosRoute: typeof AppPeriodosRoute
  AppVisualizarRoute: typeof AppVisualizarRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAmbientesRoute: AppAmbientesRoute,
  AppCoordenadoresRoute: AppCoordenadoresRoute,
  AppCursosRoute: AppCursosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDisciplinasRoute: AppDisciplinasRoute,
  AppDocentesRoute: AppDocentesRoute,
  AppHorariosRoute: AppHorariosRoute,
  AppLogsRoute: AppLogsRoute,
  AppPeriodosRoute: AppPeriodosRoute,
  AppVisualizarRoute: AppVisualizarRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PublicoRoute: PublicoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
